// @ts-nocheck
import { getDb } from "../api/queries/connection";
import {
  organizations,
  species,
  nurseries,
  nurseryStock,
  plantations,
  monitoringVisits,
  satelliteRecords,
  aiVerifications,
  notifications,
  tokens,
  badges,
  leaderboard,
  activityLog,
  reports,
} from "./schema";

const db = getDb();

async function seed() {
  console.log("Seeding database...");

  // ─── Organizations ───────────────────────────────────────────────────────
  const orgs = await db.insert(organizations).values([
    {
      name: "Kurigram District Administration",
      type: "government",
      description: "Local government body overseeing plantation initiatives",
      address: "District Commissioner Office, Kurigram",
      contactPerson: "Deputy Commissioner",
      contactEmail: "dc@kurigram.gov.bd",
      contactPhone: "+880 1711-000001",
      isActive: true,
    },
    {
      name: "Green Bangladesh Foundation",
      type: "ngo",
      description: "NGO focused on environmental conservation",
      address: "House 12, Road 5, Kurigram",
      contactPerson: "Dr. Farhana Rahman",
      contactEmail: "info@greenbd.org",
      contactPhone: "+880 1711-000002",
      isActive: true,
    },
    {
      name: "KrishiAI Research Lab",
      type: "research",
      description: "Agricultural technology research organization",
      address: "Dhaka University Campus",
      contactPerson: "Prof. Abdullah Al Mamun",
      contactEmail: "research@krishiai.dev",
      contactPhone: "+880 1711-000003",
      isActive: true,
    },
    {
      name: "Bharot Community Group",
      type: "community",
      description: "Local community-based plantation group",
      address: "Bharot Union, Kurigram Sadar",
      contactPerson: "Mohammad Ali",
      contactEmail: "bharot.group@gmail.com",
      contactPhone: "+880 1711-000004",
      isActive: true,
    },
    {
      name: "Rangpur Timber Ltd",
      type: "private",
      description: "Sustainable timber and forestry company",
      address: "Rangpur Business Center",
      contactPerson: "Kamal Hossain",
      contactEmail: "info@rangpurtimber.com",
      contactPhone: "+880 1711-000005",
      isActive: true,
    },
  ]);
  console.log("Seeded 5 organizations");

  // ─── Species ─────────────────────────────────────────────────────────────
  const specs = await db.insert(species).values([
    {
      commonName: "Mahogany",
      scientificName: "Swietenia macrophylla",
      family: "Meliaceae",
      category: "timber",
      growthRate: "moderate",
      maxHeight: 30,
      lifespan: 100,
      waterRequirement: "moderate",
      soilType: "Well-drained loamy",
      nativeRegion: "Central America",
      conservationStatus: "vulnerable",
      uses: "Furniture, construction, musical instruments",
      description: "Highly valued tropical hardwood species",
    },
    {
      commonName: "Mango",
      scientificName: "Mangifera indica",
      family: "Anacardiaceae",
      category: "fruit",
      growthRate: "moderate",
      maxHeight: 35,
      lifespan: 300,
      waterRequirement: "moderate",
      soilType: "Deep well-drained loamy",
      nativeRegion: "South Asia",
      conservationStatus: "least_concern",
      uses: "Fruit, timber, shade",
      description: "King of fruits, widely cultivated",
    },
    {
      commonName: "Neem",
      scientificName: "Azadirachta indica",
      family: "Meliaceae",
      category: "medicinal",
      growthRate: "fast",
      maxHeight: 20,
      lifespan: 200,
      waterRequirement: "low",
      soilType: "Wide range including degraded soils",
      nativeRegion: "South Asia",
      conservationStatus: "least_concern",
      uses: "Medicinal, pesticide, timber",
      description: "Versatile tree with medicinal properties",
    },
    {
      commonName: "Sundari",
      scientificName: "Heritiera fomes",
      family: "Malvaceae",
      category: "mangrove",
      growthRate: "slow",
      maxHeight: 25,
      lifespan: 200,
      waterRequirement: "high",
      soilType: "Brackish water tidal mud",
      nativeRegion: "Sundarbans",
      conservationStatus: "endangered",
      uses: "Timber, honey production",
      description: "Premier mangrove species of Sundarbans",
    },
    {
      commonName: "Narrow-leafed Ashoka",
      scientificName: "Saraca asoca",
      family: "Fabaceae",
      category: "ornamental",
      growthRate: "moderate",
      maxHeight: 10,
      lifespan: 100,
      waterRequirement: "moderate",
      soilType: "Rich well-drained",
      nativeRegion: "South Asia",
      conservationStatus: "vulnerable",
      uses: "Ornamental, medicinal",
      description: "Sacred tree with beautiful flowers",
    },
    {
      commonName: "Rain Tree",
      scientificName: "Samanea saman",
      family: "Fabaceae",
      category: "shade",
      growthRate: "fast",
      maxHeight: 25,
      lifespan: 100,
      waterRequirement: "moderate",
      soilType: "Tolerant of various soils",
      nativeRegion: "Central/South America",
      conservationStatus: "least_concern",
      uses: "Shade, timber, fodder",
      description: "Excellent shade tree for agroforestry",
    },
    {
      commonName: "Blackboard Tree",
      scientificName: "Alstonia scholaris",
      family: "Apocynaceae",
      category: "timber",
      growthRate: "fast",
      maxHeight: 40,
      lifespan: 150,
      waterRequirement: "low",
      soilType: "Various including poor soils",
      nativeRegion: "South/Southeast Asia",
      conservationStatus: "least_concern",
      uses: "Timber, medicinal",
      description: "Fast-growing useful timber species",
    },
    {
      commonName: "Jackfruit",
      scientificName: "Artocarpus heterophyllus",
      family: "Moraceae",
      category: "fruit",
      growthRate: "moderate",
      maxHeight: 20,
      lifespan: 100,
      waterRequirement: "moderate",
      soilType: "Deep well-drained",
      nativeRegion: "South/Southeast Asia",
      conservationStatus: "least_concern",
      uses: "Fruit, timber, fodder",
      description: "Largest tree-borne fruit",
    },
    {
      commonName: "Eucalyptus",
      scientificName: "Eucalyptus camaldulensis",
      family: "Myrtaceae",
      category: "timber",
      growthRate: "fast",
      maxHeight: 45,
      lifespan: 200,
      waterRequirement: "high",
      soilType: "Various including degraded soils",
      nativeRegion: "Australia",
      conservationStatus: "least_concern",
      uses: "Timber, pulp, honey",
      description: "Fast-growing timber species",
    },
    {
      commonName: "Leucaena",
      scientificName: "Leucaena leucocephala",
      family: "Fabaceae",
      category: "nitrogen_fixing",
      growthRate: "fast",
      maxHeight: 20,
      lifespan: 50,
      waterRequirement: "low",
      soilType: "Poor degraded soils",
      nativeRegion: "Central America",
      conservationStatus: "least_concern",
      uses: "Fodder, fuel, soil improvement",
      description: "Excellent nitrogen-fixing tree",
    },
  ]);
  console.log("Seeded 10 species");

  // ─── Nurseries ───────────────────────────────────────────────────────────
  const nurs = await db.insert(nurseries).values([
    {
      name: "Kurigram Central Nursery",
      organizationId: 1,
      location: "Kurigram Sadar",
      latitude: "25.8054",
      longitude: "89.6362",
      capacity: 50000,
      managerName: "Abdul Karim",
      managerContact: "+880 1711-000010",
      description: "Main government nursery serving Kurigram district",
      isActive: true,
    },
    {
      name: "Bharot Community Nursery",
      organizationId: 4,
      location: "Bharot Union",
      latitude: "25.7500",
      longitude: "89.6000",
      capacity: 15000,
      managerName: "Mohammad Ali",
      managerContact: "+880 1711-000011",
      description: "Community-managed nursery",
      isActive: true,
    },
    {
      name: "Green BD Model Nursery",
      organizationId: 2,
      location: "Kurigram Town",
      latitude: "25.8200",
      longitude: "89.6400",
      capacity: 25000,
      managerName: "Dr. Farhana Rahman",
      managerContact: "+880 1711-000012",
      description: "Research-oriented modern nursery",
      isActive: true,
    },
    {
      name: "Rajipur Nursery Station",
      organizationId: 1,
      location: "Rajipur Union",
      latitude: "25.7000",
      longitude: "89.5800",
      capacity: 20000,
      managerName: "Rafiq Islam",
      managerContact: "+880 1711-000013",
      description: "Satellite nursery for southern Kurigram",
      isActive: true,
    },
  ]);
  console.log("Seeded 4 nurseries");

  // ─── Nursery Stock ───────────────────────────────────────────────────────
  await db.insert(nurseryStock).values([
    { nurseryId: 1, speciesId: 1, quantity: 5000, age: 6, batchNumber: "KC-2025-01", source: "Seed collection", healthStatus: "excellent" },
    { nurseryId: 1, speciesId: 2, quantity: 8000, age: 4, batchNumber: "KC-2025-02", source: "Grafting", healthStatus: "good" },
    { nurseryId: 1, speciesId: 3, quantity: 12000, age: 3, batchNumber: "KC-2025-03", source: "Seed collection", healthStatus: "good" },
    { nurseryId: 2, speciesId: 3, quantity: 3000, age: 5, batchNumber: "BC-2025-01", source: "Seed collection", healthStatus: "good" },
    { nurseryId: 2, speciesId: 6, quantity: 2500, age: 4, batchNumber: "BC-2025-02", source: "Seed collection", healthStatus: "fair" },
    { nurseryId: 2, speciesId: 8, quantity: 4000, age: 6, batchNumber: "BC-2025-03", source: "Seed collection", healthStatus: "excellent" },
    { nurseryId: 3, speciesId: 1, quantity: 6000, age: 5, batchNumber: "GB-2025-01", source: "Tissue culture", healthStatus: "excellent" },
    { nurseryId: 3, speciesId: 7, quantity: 4000, age: 4, batchNumber: "GB-2025-02", source: "Seed collection", healthStatus: "good" },
    { nurseryId: 3, speciesId: 10, quantity: 5000, age: 3, batchNumber: "GB-2025-03", source: "Seed collection", healthStatus: "good" },
    { nurseryId: 4, speciesId: 2, quantity: 3500, age: 5, batchNumber: "RJ-2025-01", source: "Grafting", healthStatus: "good" },
    { nurseryId: 4, speciesId: 4, quantity: 2000, age: 8, batchNumber: "RJ-2025-02", source: "Wild collection", healthStatus: "fair" },
    { nurseryId: 4, speciesId: 9, quantity: 4500, age: 4, batchNumber: "RJ-2025-03", source: "Seed collection", healthStatus: "excellent" },
  ]);
  console.log("Seeded 12 nursery stock entries");

  // ─── Plantations ─────────────────────────────────────────────────────────
  await db.insert(plantations).values([
    {
      name: "Kurigram Sadar Reforestation 2025",
      organizationId: 1,
      nurseryId: 1,
      speciesId: 3,
      type: "reforestation",
      status: "completed",
      latitude: "25.8054",
      longitude: "89.6362",
      areaHectares: "12.5000",
      totalSaplings: 15000,
      plantedDate: "2025-03-15",
      expectedCompletion: "2025-06-30",
      description: "Large-scale reforestation project in Kurigram Sadar",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Kurigram Sadar",
      unionName: "Kurigram municipality",
    },
    {
      name: "Bharot Community Forest",
      organizationId: 4,
      nurseryId: 2,
      speciesId: 8,
      type: "community",
      status: "in_progress",
      latitude: "25.7500",
      longitude: "89.6000",
      areaHectares: "3.2000",
      totalSaplings: 4000,
      plantedDate: "2025-06-01",
      expectedCompletion: "2025-09-30",
      description: "Community-driven forest plantation",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Kurigram Sadar",
      unionName: "Bharot",
    },
    {
      name: "Rajipur Agroforestry Demo",
      organizationId: 2,
      nurseryId: 4,
      speciesId: 1,
      type: "agroforestry",
      status: "maintaining",
      latitude: "25.7000",
      longitude: "89.5800",
      areaHectares: "5.8000",
      totalSaplings: 3500,
      plantedDate: "2024-07-15",
      expectedCompletion: "2025-01-15",
      description: "Demonstration agroforestry plot",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Kurigram Sadar",
      unionName: "Rajipur",
    },
    {
      name: "Nageshwari Timber Block",
      organizationId: 5,
      nurseryId: 1,
      speciesId: 9,
      type: "commercial",
      status: "in_progress",
      latitude: "25.7800",
      longitude: "89.6200",
      areaHectares: "8.0000",
      totalSaplings: 6000,
      plantedDate: "2025-04-20",
      expectedCompletion: "2025-08-30",
      description: "Commercial timber plantation",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Nageshwari",
      unionName: "Nageshwari",
    },
    {
      name: "Ulipur Mangrove Restoration",
      organizationId: 2,
      nurseryId: 4,
      speciesId: 4,
      type: "mangrove",
      status: "planned",
      latitude: "25.6500",
      longitude: "89.5500",
      areaHectares: "15.0000",
      totalSaplings: 8000,
      plantedDate: "2025-08-01",
      expectedCompletion: "2025-12-31",
      description: "Mangrove ecosystem restoration",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Ulipur",
      unionName: "Ulipur",
    },
    {
      name: "Kurigram Urban Green Belt",
      organizationId: 1,
      nurseryId: 3,
      speciesId: 5,
      type: "urban",
      status: "in_progress",
      latitude: "25.8200",
      longitude: "89.6400",
      areaHectares: "2.1000",
      totalSaplings: 2500,
      plantedDate: "2025-05-10",
      expectedCompletion: "2025-10-31",
      description: "Urban beautification project",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Kurigram Sadar",
      unionName: "Kurigram municipality",
    },
    {
      name: "Rowmari Afforestation Project",
      organizationId: 1,
      nurseryId: 1,
      speciesId: 10,
      type: "afforestation",
      status: "completed",
      latitude: "25.8800",
      longitude: "89.7000",
      areaHectares: "20.0000",
      totalSaplings: 18000,
      plantedDate: "2024-03-01",
      expectedCompletion: "2024-08-30",
      description: "Large afforestation initiative",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Rowmari",
      unionName: "Rowmari",
    },
    {
      name: "Char Afforestation 2025",
      organizationId: 4,
      nurseryId: 2,
      speciesId: 6,
      type: "afforestation",
      status: "in_progress",
      latitude: "25.7200",
      longitude: "89.6100",
      areaHectares: "6.5000",
      totalSaplings: 5000,
      plantedDate: "2025-02-15",
      expectedCompletion: "2025-07-30",
      description: "Char land stabilization planting",
      district: "Kurigram",
      division: "Rangpur",
      upazila: "Kurigram Sadar",
      unionName: "Holokhana",
    },
  ]);
  console.log("Seeded 8 plantations");

  // ─── Monitoring Visits ───────────────────────────────────────────────────
  await db.insert(monitoringVisits).values([
    {
      plantationId: 1,
      visitedBy: "Rafiq Islam",
      visitDate: "2025-04-15",
      survivalRate: 92,
      averageHeight: "0.45",
      growthStage: "seedling",
      healthStatus: "excellent",
      maintenanceDone: "Weeding, mulching",
      notes: "Excellent survival rate observed",
    },
    {
      plantationId: 1,
      visitedBy: "Dr. Farhana Rahman",
      visitDate: "2025-06-20",
      survivalRate: 88,
      averageHeight: "0.82",
      growthStage: "sapling",
      healthStatus: "good",
      maintenanceDone: "Irrigation, pest control",
      notes: "Good progress, minor pest issue resolved",
    },
    {
      plantationId: 3,
      visitedBy: "Abdul Karim",
      visitDate: "2025-05-10",
      survivalRate: 85,
      averageHeight: "1.20",
      growthStage: "juvenile",
      healthStatus: "good",
      maintenanceDone: "Pruning, fertilization",
      notes: "Agroforestry system working well",
    },
    {
      plantationId: 3,
      visitedBy: "Prof. Mamun",
      visitDate: "2025-06-15",
      survivalRate: 83,
      averageHeight: "1.45",
      growthStage: "juvenile",
      healthStatus: "good",
      maintenanceDone: "Companion crop management",
      notes: "Intercropping showing positive results",
    },
    {
      plantationId: 7,
      visitedBy: "Mohammad Ali",
      visitDate: "2024-06-10",
      survivalRate: 78,
      averageHeight: "0.65",
      growthStage: "seedling",
      healthStatus: "fair",
      maintenanceDone: "Replanting, fencing repair",
      notes: "Some losses due to flooding",
    },
    {
      plantationId: 7,
      visitedBy: "Rafiq Islam",
      visitDate: "2024-09-20",
      survivalRate: 82,
      averageHeight: "1.10",
      growthStage: "sapling",
      healthStatus: "good",
      maintenanceDone: "Gap filling, weeding",
      notes: "Recovery after initial losses",
    },
    {
      plantationId: 7,
      visitedBy: "Dr. Farhana",
      visitDate: "2025-03-15",
      survivalRate: 86,
      averageHeight: "2.10",
      growthStage: "juvenile",
      healthStatus: "good",
      maintenanceDone: "Thinning, soil conservation",
      notes: "Excellent recovery and growth",
    },
    {
      plantationId: 4,
      visitedBy: "Kamal Hossain",
      visitDate: "2025-05-25",
      survivalRate: 90,
      averageHeight: "0.35",
      growthStage: "seedling",
      healthStatus: "excellent",
      maintenanceDone: "Regular irrigation",
      notes: "Commercial plantation on track",
    },
    {
      plantationId: 8,
      visitedBy: "Mohammad Ali",
      visitDate: "2025-03-20",
      survivalRate: 75,
      averageHeight: "0.55",
      growthStage: "seedling",
      healthStatus: "fair",
      pestDiseaseObserved: true,
      pestDiseaseDetails: "Termite attack on 5% of saplings",
      maintenanceDone: "Termite treatment applied",
      notes: "Termite issue under control",
    },
    {
      plantationId: 8,
      visitedBy: "Abdul Karim",
      visitDate: "2025-05-30",
      survivalRate: 80,
      averageHeight: "0.95",
      growthStage: "sapling",
      healthStatus: "good",
      maintenanceDone: "Follow-up treatment, weeding",
      notes: "Good recovery after termite treatment",
    },
    {
      plantationId: 2,
      visitedBy: "Mohammad Ali",
      visitDate: "2025-07-01",
      survivalRate: 88,
      averageHeight: "0.25",
      growthStage: "seedling",
      healthStatus: "good",
      maintenanceDone: "Community weeding day",
      notes: "Community engagement strong",
    },
  ]);
  console.log("Seeded 11 monitoring visits");

  // ─── Satellite Records ───────────────────────────────────────────────────
  await db.insert(satelliteRecords).values([
    {
      plantationId: 1,
      captureDate: "2025-04-01",
      ndviAverage: "0.4200",
      ndviMin: "0.1500",
      ndviMax: "0.6800",
      eviAverage: "0.3100",
      dataSource: "sentinel2",
      cloudCover: 15,
      anomalyFlags: null,
    },
    {
      plantationId: 1,
      captureDate: "2025-05-15",
      ndviAverage: "0.5800",
      ndviMin: "0.2800",
      ndviMax: "0.7800",
      eviAverage: "0.4500",
      dataSource: "sentinel2",
      cloudCover: 8,
      anomalyFlags: null,
    },
    {
      plantationId: 1,
      captureDate: "2025-06-25",
      ndviAverage: "0.6500",
      ndviMin: "0.3800",
      ndviMax: "0.8200",
      eviAverage: "0.5200",
      dataSource: "sentinel2",
      cloudCover: 5,
      anomalyFlags: null,
    },
    {
      plantationId: 3,
      captureDate: "2025-04-10",
      ndviAverage: "0.5200",
      ndviMin: "0.2500",
      ndviMax: "0.7200",
      eviAverage: "0.4100",
      dataSource: "sentinel2",
      cloudCover: 12,
      anomalyFlags: null,
    },
    {
      plantationId: 3,
      captureDate: "2025-06-10",
      ndviAverage: "0.6100",
      ndviMin: "0.3200",
      ndviMax: "0.8000",
      eviAverage: "0.5000",
      dataSource: "sentinel2",
      cloudCover: 3,
      anomalyFlags: null,
    },
    {
      plantationId: 7,
      captureDate: "2024-05-01",
      ndviAverage: "0.3500",
      ndviMin: "0.1000",
      ndviMax: "0.5500",
      eviAverage: "0.2500",
      dataSource: "landsat8",
      cloudCover: 20,
    },
    {
      plantationId: 7,
      captureDate: "2024-08-15",
      ndviAverage: "0.4800",
      ndviMin: "0.1800",
      ndviMax: "0.7000",
      eviAverage: "0.3800",
      dataSource: "sentinel2",
      cloudCover: 10,
    },
    {
      plantationId: 7,
      captureDate: "2025-02-01",
      ndviAverage: "0.5500",
      ndviMin: "0.2200",
      ndviMax: "0.7800",
      eviAverage: "0.4400",
      dataSource: "sentinel2",
      cloudCover: 5,
      anomalyFlags: "Healthy canopy growth",
    },
    {
      plantationId: 4,
      captureDate: "2025-06-01",
      ndviAverage: "0.4500",
      ndviMin: "0.1500",
      ndviMax: "0.6800",
      eviAverage: "0.3500",
      dataSource: "sentinel2",
      cloudCover: 18,
    },
  ]);
  console.log("Seeded 9 satellite records");

  // ─── AI Verifications ────────────────────────────────────────────────────
  await db.insert(aiVerifications).values([
    {
      plantationId: 1,
      type: "count_validation",
      status: "approved",
      aiConfidence: "0.9400",
      detectedCount: 14280,
      humanVerified: true,
      verifiedBy: "Dr. Farhana",
      result: { method: "aerial_count", accuracy: 0.94, falsePositive: 0.03 },
      notes: "Count validated via drone survey",
    },
    {
      plantationId: 1,
      type: "survival_check",
      status: "approved",
      aiConfidence: "0.9100",
      detectedCount: 13800,
      humanVerified: true,
      verifiedBy: "Rafiq Islam",
      result: { survivalRate: 0.92, method: "spectral_analysis" },
      notes: "Spectral analysis confirms 92% survival",
    },
    {
      plantationId: 3,
      type: "species_id",
      status: "approved",
      aiConfidence: "0.9800",
      humanVerified: true,
      verifiedBy: "Prof. Mamun",
      result: { identifiedSpecies: "Swietenia macrophylla", matchConfidence: 0.98 },
      notes: "Species identification confirmed",
    },
    {
      plantationId: 4,
      type: "geolocation_verify",
      status: "approved",
      aiConfidence: "0.9900",
      humanVerified: true,
      verifiedBy: "Kamal Hossain",
      result: { gpsAccuracy: 2.5, boundaryMatch: 0.99 },
      notes: "GPS coordinates verified accurate",
    },
    {
      plantationId: 8,
      type: "fraud_detect",
      status: "flagged",
      aiConfidence: "0.7200",
      humanVerified: false,
      result: { flags: ["location_anomaly", "timing_gap"], riskScore: 0.72 },
      notes: "Requires human review for location discrepancy",
    },
    {
      plantationId: 7,
      type: "growth_measure",
      status: "approved",
      aiConfidence: "0.8900",
      detectedCount: 15500,
      humanVerified: true,
      verifiedBy: "Dr. Farhana",
      result: { avgHeight: 2.1, canopyCover: 0.65, method: "lidar" },
      notes: "Growth measurements via LiDAR scan",
    },
  ]);
  console.log("Seeded 6 AI verifications");

  // ─── Notifications ───────────────────────────────────────────────────────
  await db.insert(notifications).values([
    { type: "monitoring_due", title: "Monitoring Visit Due", message: "Kurigram Sadar Reforestation is due for a monitoring visit.", referenceId: 1, referenceType: "plantation", actionUrl: "/monitoring" },
    { type: "alert_survival_low", title: "Low Survival Rate Alert", message: "Char Afforestation showing 75% survival rate. Threshold is 80%.", referenceId: 8, referenceType: "plantation", actionUrl: "/monitoring" },
    { type: "alert_ndvi_anomaly", title: "NDVI Anomaly Detected", message: "Ulipur Mangrove area showing unusual NDVI patterns.", referenceId: 5, referenceType: "plantation", actionUrl: "/satellite" },
    { type: "ai_verification_result", title: "AI Verification Complete", message: "Count validation for Kurigram Sadar completed with 94% confidence.", referenceId: 1, referenceType: "verification", actionUrl: "/verification" },
    { type: "token_reward", title: "Tokens Earned!", message: "You earned 150 tokens for completing monitoring visit.", referenceId: 2, referenceType: "monitoring", actionUrl: "/tokens" },
    { type: "planting_reminder", title: "Planting Season Reminder", message: "Monsoon planting season begins. Prepare your nursery stock.", referenceId: 1, referenceType: "nursery", actionUrl: "/nurseries" },
    { type: "system", title: "System Update", message: "Plantation Tracker v2.1 is now available with new features.", actionUrl: "/settings" },
    { type: "report_ready", title: "Report Ready", message: "Monthly plantation summary report is ready for download.", referenceId: 1, referenceType: "report", actionUrl: "/reports" },
  ]);
  console.log("Seeded 8 notifications");

  // ─── Tokens ──────────────────────────────────────────────────────────────
  await db.insert(tokens).values([
    { userId: 1, plantationId: 1, type: "planting", amount: 500, balance: 500, description: "Initial planting of 15,000 saplings" },
    { userId: 1, plantationId: 1, type: "monitoring", amount: 150, balance: 650, description: "First monitoring visit completed" },
    { userId: 1, plantationId: 1, type: "survival_high", amount: 300, balance: 950, description: "92% survival rate achieved" },
    { userId: 1, plantationId: 1, type: "verification", amount: 200, balance: 1150, description: "AI verification approved" },
    { userId: 1, plantationId: 7, type: "planting", amount: 600, balance: 1750, description: "Rowmari afforestation planting" },
    { userId: 1, plantationId: 7, type: "survival_milestone", amount: 250, balance: 2000, description: "Survival rate exceeded 85%" },
    { userId: 1, type: "badge_unlock", amount: 100, balance: 2100, description: "Earned First Planting badge" },
    { userId: 1, type: "community_report", amount: 75, balance: 2175, description: "Submitted community report" },
  ]);
  console.log("Seeded 8 token records");

  // ─── Badges ──────────────────────────────────────────────────────────────
  await db.insert(badges).values([
    { userId: 1, badgeType: "first_planting", level: 1, metadata: { plantationId: 1, date: "2025-03-15" } },
    { userId: 1, badgeType: "monitoring_expert", level: 2, metadata: { visits: 8, plantations: 4 } },
    { userId: 1, badgeType: "survival_champion", level: 1, metadata: { avgSurvival: 0.88 } },
    { userId: 1, badgeType: "consistent_planter", level: 1, metadata: { consecutiveMonths: 6 } },
    { userId: 1, badgeType: "carbon_warrior", level: 1, metadata: { estimatedCarbonKg: 2500 } },
  ]);
  console.log("Seeded 5 badges");

  // ─── Leaderboard ─────────────────────────────────────────────────────────
  await db.insert(leaderboard).values([
    { userId: 1, rank: 1, score: 2175, treesPlanted: 39000, treesSurvived: 33600, monitoringCount: 8, tokenBalance: 2175, badgeCount: 5, period: "all_time" },
    { userId: 2, rank: 2, score: 1850, treesPlanted: 28000, treesSurvived: 23500, monitoringCount: 6, tokenBalance: 1850, badgeCount: 4, period: "all_time" },
    { userId: 3, rank: 3, score: 1200, treesPlanted: 15000, treesSurvived: 12000, monitoringCount: 5, tokenBalance: 1200, badgeCount: 3, period: "all_time" },
    { userId: 4, rank: 4, score: 800, treesPlanted: 9000, treesSurvived: 7200, monitoringCount: 3, tokenBalance: 800, badgeCount: 2, period: "all_time" },
    { userId: 5, rank: 5, score: 450, treesPlanted: 6000, treesSurvived: 4800, monitoringCount: 2, tokenBalance: 450, badgeCount: 1, period: "all_time" },
  ]);
  console.log("Seeded 5 leaderboard entries");

  // ─── Reports ─────────────────────────────────────────────────────────────
  await db.insert(reports).values([
    {
      title: "Q2 2025 Plantation Summary",
      type: "plantation_summary",
      organizationId: 1,
      status: "ready",
      filters: { quarter: "Q2", year: 2025, district: "Kurigram" },
      fileUrl: "/reports/q2-2025-summary.pdf",
    },
    {
      title: "Kurigram Sadar NDVI Analysis",
      type: "ndvi_analysis",
      plantationId: 1,
      organizationId: 1,
      status: "ready",
      filters: { plantationId: 1, dateRange: "2025-04-01 to 2025-06-30" },
      fileUrl: "/reports/ndvi-kurigram-sadar.pdf",
    },
    {
      title: "Survival Rate Analysis 2024-2025",
      type: "survival_analysis",
      status: "ready",
      filters: { year: "2024-2025" },
      fileUrl: "/reports/survival-analysis.pdf",
    },
    {
      title: "Token Economy Report",
      type: "token_report",
      status: "ready",
      filters: { period: "all_time" },
      fileUrl: "/reports/token-economy.pdf",
    },
    {
      title: "Monthly Monitoring Report - June",
      type: "monitoring_report",
      status: "generating",
      filters: { month: 6, year: 2025 },
    },
  ]);
  console.log("Seeded 5 reports");

  // ─── Activity Log ────────────────────────────────────────────────────────
  await db.insert(activityLog).values([
    { userId: 1, action: "create", entityType: "plantation", entityId: 1, details: { name: "Kurigram Sadar Reforestation 2025" } },
    { userId: 1, action: "monitor", entityType: "plantation", entityId: 1, details: { type: "monitoring_visit", result: "excellent" } },
    { userId: 1, action: "verify", entityType: "plantation", entityId: 1, details: { type: "ai_verification", confidence: 0.94 } },
    { userId: 2, action: "create", entityType: "plantation", entityId: 3, details: { name: "Rajipur Agroforestry Demo" } },
    { userId: 2, action: "monitor", entityType: "plantation", entityId: 3, details: { type: "monitoring_visit", survivalRate: 0.85 } },
    { userId: 3, action: "create", entityType: "nursery", entityId: 3, details: { name: "Green BD Model Nursery" } },
    { userId: 4, action: "plant", entityType: "plantation", entityId: 2, details: { saplings: 4000, species: "Jackfruit" } },
    { userId: 1, action: "login", details: { ip: "192.168.1.1", device: "web" } },
    { userId: 1, action: "report", entityType: "report", entityId: 1, details: { type: "plantation_summary", generated: true } },
    { userId: 1, action: "update", entityType: "plantation", entityId: 8, details: { field: "status", from: "planned", to: "in_progress" } },
  ]);
  console.log("Seeded 10 activity log entries");

  console.log("Seeding complete!");
}

seed().catch(console.error);
